// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skvdyypcahkmgmynhcoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrdmR5eXBjYWhrbWdteW5oY29hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MzcxMTgsImV4cCI6MjA2MDMxMzExOH0.ITkwy3t5R6DWhY-WAXvW_PJJk0gygAk5J_vQnG9EytU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);